package gov.nara.nwts.ftapp;

import gov.nara.nwts.ftapp.stats.Stats;

import java.io.File;
import java.util.TreeMap;
/**
 * This class contains details about the completion of a {@link gov.nara.nwts.ftapp.filetest.FileTest} or a {@link gov.nara.nwts.ftapp.importer.Importer}
 * @author TBrady
 *
 */
public class ActionResult {
	/**
	 * Unique name to assign to the results of the action
	 */
	public String name;
	/**
	 * Descriptive name of the action that was performed
	 */
	public String action;
	/** 
	 * Root directory or file on which the action was performed
	 */
	public File root;
	/**
	 * Descriptive structure defining the components of the action results
	 */
	public Object[][] details;
	/**
	 * Container of the stats generated by the action
	 */
	public TreeMap<String,Stats>types;
	/**
	 * Indicates whether or not the task ran to completion or if the task was terminated manually or terminated by the file count threshold
	 */
	public boolean completed;
	/**
	 * Time in milliseconds that the action took to complete
	 */
	public double duration;

	public ActionResult(File root, String name, String action, Object[][] details, TreeMap<String,Stats>types, boolean completed, double duration) {
		this.root = root;
		this.name = name;
		this.action = action;
		this.details = details;
		this.types = types;
		this.completed = completed;
		this.duration = duration;
	}
}

